package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.AlembicVersion;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AlembicVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alembic_version
     *
     * @mbg.generated Mon Mar 11 20:29:47 CST 2019
     */
    int insert(AlembicVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alembic_version
     *
     * @mbg.generated Mon Mar 11 20:29:47 CST 2019
     */
    int insertSelective(AlembicVersion record);
}