package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoCommentLike;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InfoCommentLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_comment_like
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insert(InfoCommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_comment_like
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insertSelective(InfoCommentLike record);
}