package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoComment;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InfoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_comment
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insert(InfoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_comment
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insertSelective(InfoComment record);
}