package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoUser;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface InfoUserRepository  extends JpaRepository<InfoUser,Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
//    int insert(InfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
//    int insertSelective(InfoUser record);
}