package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoUserFans;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface InfoUserFansRepository  extends JpaRepository<InfoUserFans,Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user_fans
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
//    int insert(InfoUserFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user_fans
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
//    int insertSelective(InfoUserFans record);
}