package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoUser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InfoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insert(InfoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_user
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insertSelective(InfoUser record);
}