package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoNews;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InfoNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_news
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insert(InfoNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_news
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insertSelective(InfoNews record);
}