package cn.edu.csu.information.dao;

import cn.edu.csu.information.dataObject.InfoCategory;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InfoCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_category
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insert(InfoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_category
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    int insertSelective(InfoCategory record);
}