package cn.edu.csu.information.dataObject;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

@Entity
public class InfoCommentLike implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_comment_like.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_comment_like.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_comment_like.comment_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    @Id
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_comment_like.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */

    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_comment_like
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_comment_like.create_time
     *
     * @return the value of info_comment_like.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_comment_like.create_time
     *
     * @param createTime the value for info_comment_like.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_comment_like.update_time
     *
     * @return the value of info_comment_like.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_comment_like.update_time
     *
     * @param updateTime the value for info_comment_like.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_comment_like.comment_id
     *
     * @return the value of info_comment_like.comment_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_comment_like.comment_id
     *
     * @param commentId the value for info_comment_like.comment_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_comment_like.user_id
     *
     * @return the value of info_comment_like.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_comment_like.user_id
     *
     * @param userId the value for info_comment_like.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}