package cn.edu.csu.information.dataObject;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.io.Serializable;

@Entity
public class InfoUserFans implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user_fans.follower_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    @Id
    private Integer followerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user_fans.followed_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer followedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_user_fans
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user_fans.follower_id
     *
     * @return the value of info_user_fans.follower_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user_fans.follower_id
     *
     * @param followerId the value for info_user_fans.follower_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setFollowerId(Integer followerId) {
        this.followerId = followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user_fans.followed_id
     *
     * @return the value of info_user_fans.followed_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getFollowedId() {
        return followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user_fans.followed_id
     *
     * @param followedId the value for info_user_fans.followed_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setFollowedId(Integer followedId) {
        this.followedId = followedId;
    }
}