package cn.edu.csu.information.dataObject;

import java.io.Serializable;
import java.util.Date;

public class InfoCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_category.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_category.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_category.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_category.name
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_category
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_category.create_time
     *
     * @return the value of info_category.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_category.create_time
     *
     * @param createTime the value for info_category.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_category.update_time
     *
     * @return the value of info_category.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_category.update_time
     *
     * @param updateTime the value for info_category.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_category.id
     *
     * @return the value of info_category.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_category.id
     *
     * @param id the value for info_category.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_category.name
     *
     * @return the value of info_category.name
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_category.name
     *
     * @param name the value for info_category.name
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}