package cn.edu.csu.information.dataObject;

import java.io.Serializable;
import java.util.Date;

public class InfoUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.nick_name
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.password_hash
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.mobile
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.avatar_url
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.last_login
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.is_admin
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Boolean isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.signature
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user.gender
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_user
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.create_time
     *
     * @return the value of info_user.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.create_time
     *
     * @param createTime the value for info_user.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.update_time
     *
     * @return the value of info_user.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.update_time
     *
     * @param updateTime the value for info_user.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.id
     *
     * @return the value of info_user.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.id
     *
     * @param id the value for info_user.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.nick_name
     *
     * @return the value of info_user.nick_name
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.nick_name
     *
     * @param nickName the value for info_user.nick_name
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.password_hash
     *
     * @return the value of info_user.password_hash
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.password_hash
     *
     * @param passwordHash the value for info_user.password_hash
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.mobile
     *
     * @return the value of info_user.mobile
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.mobile
     *
     * @param mobile the value for info_user.mobile
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.avatar_url
     *
     * @return the value of info_user.avatar_url
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.avatar_url
     *
     * @param avatarUrl the value for info_user.avatar_url
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.last_login
     *
     * @return the value of info_user.last_login
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.last_login
     *
     * @param lastLogin the value for info_user.last_login
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.is_admin
     *
     * @return the value of info_user.is_admin
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.is_admin
     *
     * @param isAdmin the value for info_user.is_admin
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.signature
     *
     * @return the value of info_user.signature
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.signature
     *
     * @param signature the value for info_user.signature
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user.gender
     *
     * @return the value of info_user.gender
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user.gender
     *
     * @param gender the value for info_user.gender
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }
}