package cn.edu.csu.information.dataObject;

import cn.edu.csu.information.dataObject.multiKeys.InfoUserCollectionMultiKey;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import java.io.Serializable;
import java.util.Date;

@Entity
@IdClass(InfoUserCollectionMultiKey.class)
public class InfoUserCollection implements Serializable {

    @Id
    private Integer userId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user_collection.news_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */

    @Id
    private Integer newsId;

    private Date createTime;

    private static final long serialVersionUID = 1L;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getNewsId() {
        return newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}