package cn.edu.csu.information.dataObject;

import java.io.Serializable;
import java.util.Date;

public class InfoNews implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.title
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.source
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.digest
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String digest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.clicks
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer clicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.index_image_url
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String indexImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.category_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.status
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.reason
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_news.content
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_news
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.create_time
     *
     * @return the value of info_news.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.create_time
     *
     * @param createTime the value for info_news.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.update_time
     *
     * @return the value of info_news.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.update_time
     *
     * @param updateTime the value for info_news.update_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.id
     *
     * @return the value of info_news.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.id
     *
     * @param id the value for info_news.id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.title
     *
     * @return the value of info_news.title
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.title
     *
     * @param title the value for info_news.title
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.source
     *
     * @return the value of info_news.source
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.source
     *
     * @param source the value for info_news.source
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.digest
     *
     * @return the value of info_news.digest
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.digest
     *
     * @param digest the value for info_news.digest
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.clicks
     *
     * @return the value of info_news.clicks
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.clicks
     *
     * @param clicks the value for info_news.clicks
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.index_image_url
     *
     * @return the value of info_news.index_image_url
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getIndexImageUrl() {
        return indexImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.index_image_url
     *
     * @param indexImageUrl the value for info_news.index_image_url
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setIndexImageUrl(String indexImageUrl) {
        this.indexImageUrl = indexImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.category_id
     *
     * @return the value of info_news.category_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.category_id
     *
     * @param categoryId the value for info_news.category_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.user_id
     *
     * @return the value of info_news.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.user_id
     *
     * @param userId the value for info_news.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.status
     *
     * @return the value of info_news.status
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.status
     *
     * @param status the value for info_news.status
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.reason
     *
     * @return the value of info_news.reason
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.reason
     *
     * @param reason the value for info_news.reason
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_news.content
     *
     * @return the value of info_news.content
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_news.content
     *
     * @param content the value for info_news.content
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}