package cn.edu.csu.information.dataObject;

import cn.edu.csu.information.dataObject.multiKeys.InfoUserCollectionMultiKey;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import java.io.Serializable;
import java.util.Date;

@Entity
@IdClass(InfoUserCollectionMultiKey.class)
public class InfoUserCollection implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user_collection.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    @Id
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user_collection.news_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */

    @Id
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_user_collection.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_user_collection
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user_collection.user_id
     *
     * @return the value of info_user_collection.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user_collection.user_id
     *
     * @param userId the value for info_user_collection.user_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user_collection.news_id
     *
     * @return the value of info_user_collection.news_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user_collection.news_id
     *
     * @param newsId the value for info_user_collection.news_id
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_user_collection.create_time
     *
     * @return the value of info_user_collection.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_user_collection.create_time
     *
     * @param createTime the value for info_user_collection.create_time
     *
     * @mbg.generated Mon Mar 11 20:26:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}